---
    - name: Create homebridge container
      docker_container:
        name: homebridge
        image: oznu/homebridge:latest
        state: started
        recreate: yes
        restart_policy: always
        published_ports:
          - "8581:8581"
        volumes:
          - ./volumes/homebridge:/homebridge
