---
    - name: Create pi-hole container
      docker_container:
        name: pihole
        image: pihole/pihole:latest
        state: started
        recreate: yes
        restart_policy: always
        published_ports:
          - "53:53/tcp"
          - "53:53/udp"
          - "67:67/udp"
        volumes:
          - ./etc-pihole/:/etc/pihole/
          - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
